export const siteConfig = {
  name: "Ascenda Consultoria",
  shortName: "Ascenda",
  legalName: "Ascenda Consultoria",
  url: process.env.NEXT_PUBLIC_SITE_URL || "https://consultoriaascenda.com",
  title: "Ascenda | Marketing, Vendas e Tecnologia para Empresas",
  description:
    "O Ascenda integra marketing, vendas e tecnologia para estruturar crescimento empresarial, geração de demanda, processos comerciais, CRM, tráfego pago, social media e projetos estratégicos para empresas em todo o Brasil.",
  email: "comercial@consultoriaascenda.com",
  phone: "+5519978112013",
  whatsapp: "5519978112013",
  location: {
    city: "Artur Nogueira",
    region: "SP",
    country: "BR",
  },
  areaServed: [
    "Brasil",
    "São Paulo",
    "Interior de São Paulo",
    "Região Metropolitana de Campinas",
    "Campinas",
    "Artur Nogueira",
    "Holambra",
    "Cosmópolis",
    "Engenheiro Coelho",
    "Limeira",
    "Mogi Mirim",
    "Mogi Guaçu",
    "Paulínia",
    "Americana",
  ],
  sameAs: [
    "https://www.instagram.com/ascenda.consultoria/",
    "https://www.linkedin.com/company/ascenda-consultoria/",
  ],
  founders: [
    {
      name: "Alisson Almeida",
      jobTitle: "Estratégia Comercial",
      sameAs: [
        "https://www.linkedin.com/in/alisson-almeida-940ba314b/",
        "https://www.instagram.com/alisson.almeidaofc/",
      ],
    },
    {
      name: "Micaely Fontana",
      jobTitle: "Marketing e Estratégia Digital",
      sameAs: [
        "https://www.linkedin.com/company/ascenda-consultoria/",
        "https://www.instagram.com/ascenda.consultoria/",
      ],
    },
  ],
  services: [
    "Consultoria de marketing",
    "Agência de marketing",
    "Marketing digital para empresas",
    "Gestão de tráfego pago",
    "Social media estratégico",
    "Landing pages para captação de leads",
    "Consultoria comercial",
    "Consultoria de vendas",
    "Estruturação comercial",
    "Processos comerciais",
    "Treinamento comercial",
    "Implementação de CRM",
    "CRM e integrações",
    "Governança de dados",
    "Tecnologia para vendas e marketing",
    "Sistemas sob medida",
    "Consultoria de marketing em Artur Nogueira",
    "Agência de marketing em Artur Nogueira",
    "Marketing digital em Artur Nogueira",
    "Consultoria comercial em Artur Nogueira",
  ],
  keywords: [
    "marketing vendas e tecnologia",
    "consultoria de marketing",
    "agência de marketing",
    "marketing digital para empresas",
    "gestão de tráfego pago",
    "social media estratégico",
    "consultoria comercial",
    "consultoria de vendas",
    "estruturação comercial",
    "processos comerciais",
    "CRM para vendas",
    "implementação de CRM",
    "automação comercial",
    "tecnologia para marketing e vendas",
    "governança de dados",
    "crescimento empresarial",
    "geração de demanda",
    "previsibilidade de vendas",
    "Ascenda Consultoria",
    "agência de marketing em Artur Nogueira",
    "marketing digital Artur Nogueira",
    "consultoria de marketing Artur Nogueira",
    "consultoria comercial Artur Nogueira",
    "consultoria de vendas Artur Nogueira",
    "gestão de tráfego pago Artur Nogueira",
    "social media Artur Nogueira",
    "marketing e vendas Campinas",
    "consultoria empresarial interior de SP",
  ],
  localSeoPages: [
    {
      path: "/agencia-de-marketing-artur-nogueira",
      title: "Agência de Marketing em Artur Nogueira | Ascenda",
      description:
        "Soluções de marketing, vendas e tecnologia para empresas de Artur Nogueira, região de Campinas e negócios que buscam crescimento estruturado.",
    },
  ],
}

export function absoluteUrl(path = "") {
  const baseUrl = siteConfig.url.replace(/\/$/, "")
  const cleanPath = path.startsWith("/") ? path : `/${path}`
  return `${baseUrl}${cleanPath}`
}
